server:
  port: 9090
  multipart:
    enabled: true
    max-file-size: 900000000  #900M
    max-request-size: 900000000

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: quankm
    password: admin

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect

  mail:
    host: smtp.gmail.com
    username: thuhientd999@gmail.com
    password: thuhien999
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secretKey: de6aaeabadeccc598160172044da9c566242ae3b
      tokenValidityMilliseconds: 86400000
      rememberMeTokenValiditySeconds: 25920000000

logging:
  level:
    ROOT: DEBUG



